
// m.abuladze@fz-juelich.de
//
//

#include <iostream>

#include "TSystem.h"
#include "TROOT.h"
#include "TFile.h"
#include "TTree.h"
#include "TBrowser.h"
//#include "TFolder.h"
//#include "TObject.h"

#include "TH1D.h"
#include "TH2D.h"
#include "TCanvas.h"

// structures to analyse
TFile  *FileIn;
TTree  *tG4;

//  configuration
const Int_t     NofCryInArms = 12;
const Int_t     NofCrnCry = 4;
const Int_t     NofCrystals = 4 * NofCryInArms + NofCrnCry;

const Int_t     NofScintilators = 4;

const Int_t     NofCanvases = 6;

//  numbers indicating direction(U, D, R, L) of next 12 objects in list
Int_t Ls = 0;
Int_t Rs = 1 * NofCryInArms;
Int_t Us = 2 * NofCryInArms;
Int_t Ds = 3 * NofCryInArms;

//  index of first corner cristal in list of histograms
Int_t Crns = 4 * NofCryInArms;

// structures which store information from one entry
Int_t           eventID;
Double_t        Particle;
Double_t        Kinetic_Energy;
Double_t        theta_lab;
Double_t        phi_lab;

Double_t        histInfo[NofCrystals];
Double_t        ScinInfo[NofScintilators];

// sorting of the crystals coresponds from left to right, up to down.
// according to the TCanvas numbering
Char_t szRCry[NofCryInArms][7] = {
"R1_1_3", // upper row
"R2_2_5",
"R3_3_7",
"R4_3_7",
"R1_2_3", // middle 
"R2_3_5",
"R3_4_7",
"R4_4_7",
"R1_3_3", // lower
"R2_4_5",
"R3_5_7",
"R4_5_7"};

Char_t szLCry[NofCryInArms][7] = {
"L4_5_7", // upper row
"L3_5_7",
"L2_4_5",
"L1_3_3",
"L4_4_7", //  middle
"L3_4_7",
"L2_3_5",
"L1_2_3",
"L4_3_7", //  lower
"L3_3_7",
"L2_2_5",
"L1_1_3"};

Char_t szUCry[NofCryInArms][7] = {
"U4_3_7",   // first row
"U4_4_7",
"U4_5_7",
"U3_3_7",   // second row
"U3_4_7",
"U3_5_7",
"U2_2_5",   // 3rd row
"U2_3_5",
"U2_4_5",
"U1_1_3",   // 4th row
"U1_2_3",
"U1_3_3"};

Char_t szDCry[NofCryInArms][7] = {
"D1_2_3",   // first row
"D1_3_3",
"D1_1_3",
"D2_4_5",   // second row
"D2_3_5",
"D2_2_5",
"D3_5_7",   // 3rd row
"D3_4_7",
"D3_3_7",
"D4_5_7",   // 4th row
"D4_4_7",
"D4_3_7"};


//  names of corner crystals
Char_t szCrnCry[NofCrnCry][7] = {"C1_1_4", "C1_2_4", "C1_3_4", "C1_4_4"};

//  names of scintillators
Char_t namesOfScintilators[NofScintilators][8] = {"kE_dE_R", "kE_dE_L", "kE_dE_U", "kE_dE_D"};

//  names of canvases 
Char_t namesOfCanvases[NofCanvases][55] = {"Left_detectors", "Right_detectors", "Up_detectors", "Down_detectors",
"C_detectors", "Scintilators"};

// histograms 
TH1D    *h_eventID;   
TH1D    *h_Particle;   
TH1D    *h_Kinetic_Energy;
TH1D    *h_phi_lab;
TH1D    *h_theta_lab;

TH1D    *hLYSO[NofCrystals];
TH1D    *hDESC[NofScintilators];

TH2D    *hThetaVSPhi;
TH2D    *hdEvsE[4 * NofCryInArms];

//=============================================================================
void HistInit(){
   gROOT->cd(); //extremely neccessary
   h_eventID = new TH1D("h_eventID",";", 1010, -10, 300);   
   h_Particle = new TH1D("h_Particle",";", 1010, -10, 300);
   h_Kinetic_Energy = new TH1D("h_Kinetic_Energy",";", 1010, -10, 300);
   h_theta_lab = new TH1D("h_theta_lab",";", 1010, -10, 10);
   h_phi_lab = new TH1D("h_phi_lab",";", 1010, -10, 10);

  // Crystals and Crystal-Scintillarot 2D histograms
  for(int i = 0; i < NofCryInArms; i++) {
    hLYSO[Ls+i]   = new TH1D( Form("h_%s", szLCry[i]), ";T_d [MeV];", 1010, -10, 300);
    hLYSO[Rs+i]   = new TH1D( Form("h_%s", szRCry[i]), ";T_d [MeV];", 1010, -10, 300);
    hLYSO[Us+i]   = new TH1D( Form("h_%s", szUCry[i]), ";T_d [MeV];", 1010, -10, 300);
    hLYSO[Ds+i]   = new TH1D( Form("h_%s", szDCry[i]), ";T_d [MeV];", 1010, -10, 300); 

    hdEvsE[Ls+i]   = new TH2D( Form("h2_dEvs%s", szLCry[i]), ";T_d [MeV];", 1010, -10, 300, 1010, -10, 300);
    hdEvsE[Rs+i]   = new TH2D( Form("h2_dEvs%s", szRCry[i]), ";T_d [MeV];", 1010, -10, 300, 1010, -10, 300);
    hdEvsE[Us+i]   = new TH2D( Form("h2_dEvs%s", szUCry[i]), ";T_d [MeV];", 1010, -10, 300, 1010, -10, 300);
    hdEvsE[Ds+i]   = new TH2D( Form("h2_dEvs%s", szDCry[i]), ";T_d [MeV];", 1010, -10, 300, 1010, -10, 300);
  }

  // Corner crystals
  for(int i = 0; i < NofScintilators; i++)
    hLYSO[Crns+i] = new TH1D( Form("h_%s", szCrnCry[i]), ";T_d [MeV];", 1010, -10, 300);

  // Scintillators
  for(int i = 0; i < NofScintilators; i++)
    hDESC[i] = new TH1D( Form("h_%s", namesOfScintilators[i]),";#Delta E [MeV];", 1010, -10, 300);

  // distribution of particles according to an angles of shoot
  hThetaVSPhi   = new TH2D("hThetaVSPhi", ";;", 1010, 0.05, 0.4, 1010, -5, 5);
}

//=============================================================================
void DefineBranchAddress(){
  //read the Tree generated by G4
  tG4->SetBranchAddress("eventID", &eventID);
  tG4->SetBranchAddress("Particle", &Particle);
  tG4->SetBranchAddress("Kinetic_Energy", &Kinetic_Energy);
  tG4->SetBranchAddress("theta_lab", &theta_lab);
  tG4->SetBranchAddress("phi_lab", &phi_lab);

// L R U D
  for(int i = 0; i < NofCryInArms; i++) {
    
    tG4->SetBranchAddress(szLCry[i], &histInfo[Ls+i]);
    tG4->SetBranchAddress(szRCry[i], &histInfo[Rs+i]);
    tG4->SetBranchAddress(szUCry[i], &histInfo[Us+i]);
    tG4->SetBranchAddress(szDCry[i], &histInfo[Ds+i]);
  }
   
// corners
  for(int i = 0; i < NofCrnCry; i++)
    tG4->SetBranchAddress(szCrnCry[i], &histInfo[Crns+i]);

// Scintillators
  for(int i = 0; i < NofScintilators; i++)
    tG4->SetBranchAddress(namesOfScintilators[i], &ScinInfo[i]);
}

//=============================================================================
void Init() {
  tG4 = (TTree*) FileIn->Get("hits"); //implementing a tree to read later

  DefineBranchAddress(); // defining address for information taken from branches to save their copies

  HistInit(); //  impleneting histograms for visualization
}

//=============================================================================
void ReadTree(){
  //read all entries and fill the histograms
  Long64_t nentries = tG4->GetEntries();

  for (int i=0;i<nentries;i++) {
    tG4->GetEntry(i);

    hThetaVSPhi->Fill(theta_lab, phi_lab); // record Events

    for (int j = 0; j < NofCrystals; j++) //LYSO infromation
      hLYSO[j]->Fill( histInfo[j] );

    for(int j = 0; j < NofCryInArms; j++){    // LYSO cristals VC Scintillator information 
      hdEvsE[Ls+j]->Fill(histInfo[Ls+j],ScinInfo[0]);
      hdEvsE[Rs+j]->Fill(histInfo[Rs+j],ScinInfo[1]);
      hdEvsE[Us+j]->Fill(histInfo[Us+j],ScinInfo[2]);
      hdEvsE[Ds+j]->Fill(histInfo[Ds+j],ScinInfo[3]);
    }

    for(int j = 0; j < NofScintilators; j++)    // Scintillator information
      hDESC[j]->Fill(ScinInfo[j]);
  }
  
  FileIn->Close();
}

//=============================================================================
//=============================================================================
void analyse(const Char_t szFileName[]="/home/mariam/simulation/output/20190510_1310/GunZpos_-10.root") {

  //TFolder *folder = new TFolder(szFolderName, "data");
  //FileIn = (TFile*) folder->FindObject("GunZpos_10.root");
  //cout << "Seiqmna imput faili " << endl;
  
  // openning file and creating to analyse
  FileIn = new TFile(szFileName);
  if(!FileIn->IsOpen()) gSystem->Exit(1);
  tG4 = (TTree*) FileIn->Get("hits");  //implementing a tree to read later

  // procesing file
  Init();
  ReadTree();
}
